### ISSUE TITLE
duplicate sample 'id'

### ISSUE THREAD

**Issue by VeritasXu** [PhoenixZ810/MG-LLaVA#1]
Dear authors, 

Many thanks for sharing the interesting work. However, there seem to be many samples with the same 'id' (about 250k) in bbox.json and annotation.json (for train) , resulting in mismatched bboxes and images.

**Comment by PhoenixZ810** [comment]
Thank you for bringing this to our attention!
 Upon re-examining the fine-tuning annotation JSON, I have confirmed that there are indeed duplicate IDs present. Nevertheless, it appears that **the same ID corresponds to different conversations yet identical images**, indicating that the bounding boxes and images remain properly aligned.

**Comment by VeritasXu** [comment]
Got that, thank you.
