### ISSUE TITLE
How to evaluate MG-LLaVA for the MMStar benchmark?

### ISSUE THREAD

**Issue by xmu-xiaoma666** [PhoenixZ810/MG-LLaVA#2]
How to evaluate MG-LLaVA for the MMStar benchmark?

**Comment by PhoenixZ810** [comment]
Thanks for your attention!
You can find the evaluation settings for MMStar in any of the SFT configs. For example, if you want to evaluate MG-LLaVA with Vicuna7B, you can refer to [config](https://github.com/PhoenixZ810/MG-LLaVA/blob/master/mg_llava/config/vicuna/fuse_more_vicuna7b_clip_L_14_336_sft_padding.py) and modify the relevant code segment:
```
dict(
        type=MultipleChoiceDataset,
        proxy_eval_dataset=dict(
            type=MGLLaVAProxyEvalDataset,
            box_json_path='PATH_TO_MMSTAR_BBOX_JSON',
            image_size_aux=image_size_aux,
            limit_num=limit_num,
        ),
        data_file='PATH_TO_MMSTAR_TSV',
        prompt_template=PROMPT_TEMPLATE.vicuna,
        tokenizer=tokenizer,
        image_processor=image_processor,
        pad_image_to_square=pad_image_to_square,
    )
```
Once you have made the necessary changes, please run test.sh with this config. :blush:
