### ISSUE TITLE
MG-LLaVA 应用问题

### ISSUE THREAD

**Issue by qingfengcss** [PhoenixZ810/MG-LLaVA#3]
您好，我想用MG llava做进一步的应用，但是在使用您开源的模型中遇到一些问题：
   huggingface上开源的模型能否用于xtuner/tools/chat.py，如果能的话，那llm_adapter就不明白如何使用，不知道能不能给一个详细的关于如何使用的readme，或者一个demo运行您开源的模型。

**Comment by PhoenixZ810** [comment]
Thank you for your interest. For detailed instructions on how to use Xtuner, please refer to the [Xtuner documentation](https://github.com/InternLM/xtuner). We are currently planning to release a demo soon.
