### ISSUE TITLE
How to prepare the data and data's path when I want to doing "inference"?

### ISSUE THREAD

**Issue by RonaldYuren** [PhoenixZ810/MG-LLaVA#7]
May I ask the question like the title when I just want use this MG-LLaVA to do inference?
I am not sure how to prepare the data and its path.
I think I just need to run the  "xtuner/tools/test.py"  ?   Or I need to run other script files ?

**Comment by PhoenixZ810** [comment]
Thanks for your attention! 
The inference code is available now.

**Comment by RonaldYuren** [comment]
I am facing with error " Traceback (most recent call last):
File "/home/MG-LLaVA/mg_llava/module/chat_utils.py", line 5, in <module>
    from ram.models import ram_plus
ModuleNotFoundError: No module named 'ram' "   

But I can't find how to install the "ram" module, does it means that "RAM" model download with Hugging Face?  or is there a place to install ?

**Comment by RonaldYuren** [comment]
> I am facing with error " Traceback (most recent call last): File "/home/MG-LLaVA/mg_llava/module/chat_utils.py", line 5, in from ram.models import ram_plus ModuleNotFoundError: No module named 'ram' "
> 
> But I can't find how to install the "ram" module, does it means that "RAM" model download with Hugging Face? or is there a place to install ?

I am facing with error " Traceback (most recent call last):
File "/home/MG-LLaVA/mg_llava/module/chat_utils.py", line 5, in
from ram.models import ram_plus
ModuleNotFoundError: No module named 'ram' "

But I can't find how to install the "ram" module, does it means that "RAM" model download with Hugging Face? or is there a place to install ?

**Comment by RonaldYuren** [comment]
> Thanks for your attention! The inference code is available now.

I am facing with error " Traceback (most recent call last):
File "/home/MG-LLaVA/mg_llava/module/chat_utils.py", line 5, in
from ram.models import ram_plus
ModuleNotFoundError: No module named 'ram' "

But I can't find how to install the "ram" module, does it means that "RAM" model download with Hugging Face? or is there a place to install ?

**Comment by PhoenixZ810** [comment]
Please refer to this [issue](https://github.com/PhoenixZ810/MG-LLaVA/issues/8).
