### ISSUE TITLE
The module "ram" seems missing

### ISSUE THREAD

**Issue by hehulingxiao** [PhoenixZ810/MG-LLaVA#8]
May I ask the question that the module "ram" seems to be missing, in Line 5-7 of MG-LLaVA/mg_llava/module/chat_utils.py?

**Comment by PhoenixZ810** [comment]
Hi,
RAM model needs to be installed from source, please clone the official code [RAM](https://github.com/xinyu1205/recognize-anything.git) and run `pip install -e .` :blush:
